// flow-typed signature: 8c3b7d581673bf9ca19d3bbb710754f6
// flow-typed version: <<STUB>>/jshint_v^2.9.5/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jshint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jshint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'jshint/data/ascii-identifier-data' {
  declare module.exports: any;
}

declare module 'jshint/data/non-ascii-identifier-part-only' {
  declare module.exports: any;
}

declare module 'jshint/data/non-ascii-identifier-start' {
  declare module.exports: any;
}

declare module 'jshint/dist/jshint-rhino' {
  declare module.exports: any;
}

declare module 'jshint/dist/jshint' {
  declare module.exports: any;
}

declare module 'jshint/src/cli' {
  declare module.exports: any;
}

declare module 'jshint/src/jshint' {
  declare module.exports: any;
}

declare module 'jshint/src/lex' {
  declare module.exports: any;
}

declare module 'jshint/src/messages' {
  declare module.exports: any;
}

declare module 'jshint/src/name-stack' {
  declare module.exports: any;
}

declare module 'jshint/src/options' {
  declare module.exports: any;
}

declare module 'jshint/src/platforms/rhino' {
  declare module.exports: any;
}

declare module 'jshint/src/reg' {
  declare module.exports: any;
}

declare module 'jshint/src/reporters/checkstyle' {
  declare module.exports: any;
}

declare module 'jshint/src/reporters/default' {
  declare module.exports: any;
}

declare module 'jshint/src/reporters/jslint_xml' {
  declare module.exports: any;
}

declare module 'jshint/src/reporters/non_error' {
  declare module.exports: any;
}

declare module 'jshint/src/reporters/unix' {
  declare module.exports: any;
}

declare module 'jshint/src/scope-manager' {
  declare module.exports: any;
}

declare module 'jshint/src/state' {
  declare module.exports: any;
}

declare module 'jshint/src/style' {
  declare module.exports: any;
}

declare module 'jshint/src/vars' {
  declare module.exports: any;
}

// Filename aliases
declare module 'jshint/data/ascii-identifier-data.js' {
  declare module.exports: $Exports<'jshint/data/ascii-identifier-data'>;
}
declare module 'jshint/data/non-ascii-identifier-part-only.js' {
  declare module.exports: $Exports<'jshint/data/non-ascii-identifier-part-only'>;
}
declare module 'jshint/data/non-ascii-identifier-start.js' {
  declare module.exports: $Exports<'jshint/data/non-ascii-identifier-start'>;
}
declare module 'jshint/dist/jshint-rhino.js' {
  declare module.exports: $Exports<'jshint/dist/jshint-rhino'>;
}
declare module 'jshint/dist/jshint.js' {
  declare module.exports: $Exports<'jshint/dist/jshint'>;
}
declare module 'jshint/src/cli.js' {
  declare module.exports: $Exports<'jshint/src/cli'>;
}
declare module 'jshint/src/jshint.js' {
  declare module.exports: $Exports<'jshint/src/jshint'>;
}
declare module 'jshint/src/lex.js' {
  declare module.exports: $Exports<'jshint/src/lex'>;
}
declare module 'jshint/src/messages.js' {
  declare module.exports: $Exports<'jshint/src/messages'>;
}
declare module 'jshint/src/name-stack.js' {
  declare module.exports: $Exports<'jshint/src/name-stack'>;
}
declare module 'jshint/src/options.js' {
  declare module.exports: $Exports<'jshint/src/options'>;
}
declare module 'jshint/src/platforms/rhino.js' {
  declare module.exports: $Exports<'jshint/src/platforms/rhino'>;
}
declare module 'jshint/src/reg.js' {
  declare module.exports: $Exports<'jshint/src/reg'>;
}
declare module 'jshint/src/reporters/checkstyle.js' {
  declare module.exports: $Exports<'jshint/src/reporters/checkstyle'>;
}
declare module 'jshint/src/reporters/default.js' {
  declare module.exports: $Exports<'jshint/src/reporters/default'>;
}
declare module 'jshint/src/reporters/jslint_xml.js' {
  declare module.exports: $Exports<'jshint/src/reporters/jslint_xml'>;
}
declare module 'jshint/src/reporters/non_error.js' {
  declare module.exports: $Exports<'jshint/src/reporters/non_error'>;
}
declare module 'jshint/src/reporters/unix.js' {
  declare module.exports: $Exports<'jshint/src/reporters/unix'>;
}
declare module 'jshint/src/scope-manager.js' {
  declare module.exports: $Exports<'jshint/src/scope-manager'>;
}
declare module 'jshint/src/state.js' {
  declare module.exports: $Exports<'jshint/src/state'>;
}
declare module 'jshint/src/style.js' {
  declare module.exports: $Exports<'jshint/src/style'>;
}
declare module 'jshint/src/vars.js' {
  declare module.exports: $Exports<'jshint/src/vars'>;
}
