// flow-typed signature: 72c5a26ca581351c775aca3695df556d
// flow-typed version: <<STUB>>/loop-protect_v^2.1.6/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'loop-protect'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'loop-protect' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'loop-protect/dist/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'loop-protect/dist/index.js' {
  declare module.exports: $Exports<'loop-protect/dist/index'>;
}
