// flow-typed signature: 14cb03dc03e3b146698192639b412563
// flow-typed version: <<STUB>>/react-tooltip_v^3.4.0/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-tooltip'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-tooltip' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-tooltip/dist/constant' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/customEvent' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/getEffect' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/isCapture' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/staticMethods' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/trackRemoval' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/decorators/windowListener' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/index' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/style' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/utils/aria' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/utils/getPosition' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/utils/getTipContent' {
  declare module.exports: any;
}

declare module 'react-tooltip/dist/utils/nodeListToArray' {
  declare module.exports: any;
}

declare module 'react-tooltip/standalone/react-tooltip' {
  declare module.exports: any;
}

declare module 'react-tooltip/standalone/react-tooltip.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-tooltip/dist/constant.js' {
  declare module.exports: $Exports<'react-tooltip/dist/constant'>;
}
declare module 'react-tooltip/dist/decorators/customEvent.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/customEvent'>;
}
declare module 'react-tooltip/dist/decorators/getEffect.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/getEffect'>;
}
declare module 'react-tooltip/dist/decorators/isCapture.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/isCapture'>;
}
declare module 'react-tooltip/dist/decorators/staticMethods.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/staticMethods'>;
}
declare module 'react-tooltip/dist/decorators/trackRemoval.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/trackRemoval'>;
}
declare module 'react-tooltip/dist/decorators/windowListener.js' {
  declare module.exports: $Exports<'react-tooltip/dist/decorators/windowListener'>;
}
declare module 'react-tooltip/dist/index.js' {
  declare module.exports: $Exports<'react-tooltip/dist/index'>;
}
declare module 'react-tooltip/dist/style.js' {
  declare module.exports: $Exports<'react-tooltip/dist/style'>;
}
declare module 'react-tooltip/dist/utils/aria.js' {
  declare module.exports: $Exports<'react-tooltip/dist/utils/aria'>;
}
declare module 'react-tooltip/dist/utils/getPosition.js' {
  declare module.exports: $Exports<'react-tooltip/dist/utils/getPosition'>;
}
declare module 'react-tooltip/dist/utils/getTipContent.js' {
  declare module.exports: $Exports<'react-tooltip/dist/utils/getTipContent'>;
}
declare module 'react-tooltip/dist/utils/nodeListToArray.js' {
  declare module.exports: $Exports<'react-tooltip/dist/utils/nodeListToArray'>;
}
declare module 'react-tooltip/standalone/react-tooltip.js' {
  declare module.exports: $Exports<'react-tooltip/standalone/react-tooltip'>;
}
declare module 'react-tooltip/standalone/react-tooltip.min.js' {
  declare module.exports: $Exports<'react-tooltip/standalone/react-tooltip.min'>;
}
