export const PANES_STATE: string = 'cs-pg-react-panesState'
export const THEME_STATE: string = 'cs-pg-react-themeState'
export const EDITR_STATE: string = 'cs-pg-react-editorState'
export const MENU_STATE: string = 'cs-pg-react-menuState'
export const RMOVE_DUPES: string = 'cs-pg-react-dupes-removed'
export const RENDR_MODAL: string = 'cs-pg-react-render-only-thrice'
export const IS_SUITE_SUPPRESSED: string = 'cs-pg-react-tests-suppressed'
export const ALL_TESTS_SUPPRESSED: string = 'cs-pg-react-suppress-tests-only-once'
