// @flow
export const MENU_STATE = 'cs-pg-react-menuState'
export const PANES_STATE = 'cs-pg-react-panesState'
export const THEME_STATE = 'cs-pg-react-themeState'
export const EDITOR_STATE = 'cs-pg-react-editorState'
export const REMOVE_DUPES = 'cs-pg-react-dupes-removed'
export const RENDER_MODAL = 'cs-pg-react-render-only-thrice'
export const IS_SUITE_SUPPRESSED = 'cs-pg-react-tests-suppressed'
export const ALL_TESTS_SUPPRESSED = 'cs-pg-react-suppress-tests-only-once'
export const IS_LOOP_PROTECT_DISABLED = 'cs-pg-react-disable-loop-protect'
export const RESET_ANNOUNCEMENT_COUNT = 'cs-pg-react-reset-announcement-count'
