export const PANES_STATE = 'cs-pg-react-panesState'
export const THEME_STATE = 'cs-pg-react-themeState'
export const EDITR_STATE = 'cs-pg-react-editorState'
export const RMOVE_DUPES = 'cs-pg-react-dupes-removed'
export const RENDR_MODAL = 'cs-pg-react-render-only-thrice'
export const ARE_TESTS_SUPPRESSED = 'cs-pg-react-tests-suppressed'
export const ALL_TESTS_SUPPRESSED = 'cs-pg-react-suppress-tests-only-once'
